### ISSUE TITLE
Different colors for play and stop

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#11]

**Comment by vmiklos** [comment]
Are you aware of other apps that do it? E.g. the stock clock app which has a start/stop button for the timer doesn't change colors. So it may make sense to not do this.

**Comment by aleksejrs** [comment]
* GNOME-Clocks makes the button blue when it's "Start" or "Continue" (was green in drafts), and red when it's "Stop": https://wiki.gnome.org/Design/Apps/Clock
* GTimer has separate buttons of different colors: http://www.k5n.us/gtimer/

**Comment by vmiklos** [comment]
Fair enough, then this makes sense.

**Comment by vmiklos** [comment]
I'll soon cut a 6.1 release, no idea if that's important for you or you are able to build from source. :-)
