### ISSUE TITLE
Scroll whole view

### ISSUE THREAD

**Issue by nhfo** [vmiklos/plees-tracker#13]
With the resigned UI (looks quite good) more than half of the vertical space is taken up by fixed content, rest of the space barely fits two records.

Presently only the record list is scrollable, it would be nice if whole screen scrolled. It would make going through records easier.

**Comment by vmiklos** [comment]
Good idea, are you interested in looking into this yourself?

I would hope that with a bit of research this is possible to do with just tweaking the layout XML, without much actual development.

**Comment by nhfo** [comment]
> Good idea, are you interested in looking into this yourself?

Unfortunately no, I have no understanding of Android development.

**Comment by vmiklos** [comment]
https://stackoverflow.com/questions/34482345/how-to-make-recyclerview-scroll-with-its-parent

That mentioned CollapsingToolBarLayout looks promising, we should probably use that for the Status and Dashboard sections.

**Comment by vmiklos** [comment]
At the end I decided to move even the "past sleeps" header to the app bar, so now everything above the sleep list scrolls.

**Comment by vmiklos** [comment]
6.2 is out, containing this.
