### ISSUE TITLE
Automatic backup does not happen after editing a sleep

### ISSUE THREAD

**Issue by shadow00** [vmiklos/plees-tracker#138]
**Reproducer steps**
1. Create a sleep with start/stop
2. Backup file gets automatically updated
3. Edit a sleep

**Actual result**
Backup file stays the same

**Expected behavior**
Backup file should get updated after editing as well. Without this, the backup stays out of date whenever a sleep is edited.

**Cause**
backupSleeps() only gets called inside startStop() inside the main activity:
https://github.com/vmiklos/plees-tracker/blob/c82a64841d883b29d18ae47f7ae6b0276b27f298/app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt#L263-L267

but not inside updateSleep():
https://github.com/vmiklos/plees-tracker/blob/c82a64841d883b29d18ae47f7ae6b0276b27f298/app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt#L71-L76

**Comment by vmiklos** [comment]
Thanks! Good catch, are you interested in sending a fix for this yourself? Your analysis sounds correct to me, so it may be reasonably straightforward to came up with a patch.

**Comment by shadow00** [comment]
Sorry, I have never used Kotlin and I don't want to make a mess of your code. The only reason why I figured this out is because the logic of your code seems pretty clean and it was easy to follow. Otherwise, I would have been happy to contribute!

**Comment by vmiklos** [comment]
No problem I was just asking. :-)

**Comment by shadow00** [comment]
By the way, I think the same problem also applies when deleting a sleep too (which seems to happen inside onCreate() in the main activity?)

**Comment by vmiklos** [comment]
> By the way, I think the same problem also applies when deleting a sleep too (which seems to happen inside onCreate() in the main activity?)

You're right, let me fix both before closing this.
