### ISSUE TITLE
Dashboard meanings are confusing

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#14]
* "Nights" means how many times you started and stopped sleeping.
* "Average" is apparently the average time between starting and stopping. That's what it was in the past, at least (I think).
* What does "Daily" mean? My guess it that it's the median time of what "Average" is based on. Also, my "Daily" is something like "95:55:11".

**Comment by vmiklos** [comment]
Yes, it was alwasy nights, though for your multi-sleep/day use-case, it should be probably rather "sleeps", not nights. :-) I'll fix that.

Daily is meant to be the avg that makes sense for your multi-sleep/day use-case, see the test:

https://github.com/vmiklos/plees-tracker/blob/8c1e14794c269afda48ed1009fb48dbe77dcd449/app/src/test/java/hu/vmiklos/plees_tracker/DataModelUnitTest.kt#L63-L98

95 hours sounds impossible in reality. Please file a separate issue for that, once you have an export for your sleep db that shows the problem. (Ideally only keep a minimum set of entries.)

**Comment by vmiklos** [comment]
Nights are now called sleeps to be clear.

**Comment by vmiklos** [comment]
6.2 is out, containing this.
