### ISSUE TITLE
Data Export Help

### ISSUE THREAD

**Issue by akashpal-21** [vmiklos/plees-tracker#15]
Hi, i don't know if this is a issue or i am doing something wrong, but i want to export the data and do analytics.
I can see there is an export option, which exports to a csv, but i cannot understand the numbers in the start and stop columns. I thought maybe they are UNIX dates, so i tried converting them but it turns out, they give me some really wild results. take for example

```
sid,start,stop
3,1588031041720,1588070163374
5,1588142846876,1588165544783

```

if we are to convert them i get something like

09/12/52292 @ 9:48pm (UTC)

Which is way beyond the mark. What should i do?

**Comment by vmiklos** [comment]
See the code:

https://github.com/vmiklos/plees-tracker/blob/65aac8d9ccca9bc3777aba918321aab26775b0f5/app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt#L68-L81

I.e. it uses <https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#getTime()>, which says:

>  number of milliseconds since January 1, 1970, 00:00:00 GMT

Perhaps you forgot to divide by 1000 before you parsed the unix timestamp?

And you're right, it would make sense to document this somewhere, so you don't need to look at the code.

**Comment by akashpal-21** [comment]
Thanks, i was converting them as seconds which caused the issue. Treating them as milliseconds solved it.
Thanks again
