### ISSUE TITLE
FR : ask for user validation before deleting a night/sleep

### ISSUE THREAD

**Issue by GLLM** [vmiklos/plees-tracker#157]
Hi,

Thanks for this nice FOSS sleep app ! Happy to have find it on F-Droid !!

Suggestion :
In the main screen, when swiping right or left on a night/sleep, the swiped item is deleted.
A user validation would be fine, or at least showing the fact that it will be deleted by showing a trashbin on the left when swiping right (resp. on the right when swiping left).

Thanks
GLLM

**Comment by vmiklos** [comment]
Hmm, a snackbar is already shown when deleting a sleep with swiping, which also allows undoing the delete if it was by accident. This is really similar to other apps, e.g. the gmail one deletes email the same way (swipe + snackbar to undo). One can argue that an "are you sure" style confirmation popup is annoying.

Do you have an example app where it works this way?

**Comment by GLLM** [comment]
Hi @vmiklos,

OK, I see the snackbar, it's nice ! 
Maybe just an icon appearing when sliding the "sleep item" to clearly indicate the user the slide is going to do something !
I'm thinking of just an icon (not a menu or anything else) such as the one you get when 
- swiping emails in GMail, Protonmail, Outlook android apps ....
![Uploading **image.png…]()**
- swiping notifications on Adnroid (at least on Samsung Galaxy phones)
thanks :)

**Comment by vmiklos** [comment]
Ah yes, such an icon makes sense.
