### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by martiandolphin** [vmiklos/plees-tracker#16]
I think a dark mode would be a valuable addition to the app, especially since it's going to be mainly used at night. I've never made an android app before but I changed some variables around after installing android studio which resulted with [this](https://gist.github.com/alvierahman90/e679934770d03f81e3db63e1c9987a12) which looks like this:

![](https://i.imgur.com/TeDCUVv.png)

Preferably the app will be able to switch between dark and light modes as android changes between dark and light mode. 

I will try to figure out how to do it myself and submit a pull request but, as I said, I've never done android development before so no guarantees.

**Comment by vmiklos** [comment]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

Try to follow this guide, hopefully it'll work out.

**Comment by vmiklos** [comment]
https://heartbeat.fritz.ai/adding-dark-mode-support-to-your-android-apps-7ee6a902165c

And this is a step by step how-to, you could try following this one :-)

**Comment by martiandolphin** [comment]
Thank you for the help. I will hopefully try the tutorial layer this week
-------- Original Message --------

**Comment by martiandolphin** [comment]
I added automatic dark mode to the app in [this commit](https://github.com/martiandolphin/plees-tracker/commit/423022364abbd9b94479bdd0b4fd0a0fca41a9bd) and an option to manually select the theme in the [next commit](https://github.com/martiandolphin/plees-tracker/commit/178ba5c9b244af5c38bbc270aef86e1b97f33047) but there are a few issues:

1. It seems that in light mode the header goes white instead of `primaryColor`. I'm not sure why that is. I would appreciate it if you could have a look.
2. The app doesn't remember when you change to theme when you next open it

**Comment by vmiklos** [comment]
Why would one want to toggle the darkness of the app manually? Either the system is in dark mode or not, and then the app is expected to be consistent with that, I guess. Adding a setting is reasonably straightforward, but don't forget that every new bool setting doubles the configuration space, so be careful.

Other than that, the easiest is if you send in a PR with the first commit, and then I'm happy to take a look. :-)

**Comment by martiandolphin** [comment]
The option to manually select theme would be nice for people who aren't on Android 10 yet as Android 9 and below do not support dark mode (to my knowledge).

I will sent a PR on the first commit.

**Comment by vmiklos** [comment]
Nah, this was auto-close. :-) Let's leave it open till the dark mode preference is added, I forgot about those poor souls who are not yet on Android 10.

**Comment by vmiklos** [comment]
See here for a guide on how to add a preference activity:

https://developer.android.com/guide/topics/ui/settings

There you could add a setting with 3 states: light mode, dark mode or "let the system decide".

And then all you need is to read this setting, as done here:

https://github.com/vmiklos/plees-tracker/blob/570c301d1a0cd6a3b7025b3753b9cef8bfcd9417/app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt#L55-L66

**Comment by vmiklos** [comment]
This is now fixed on master with commit 114b55fe19fa99372d5d67a4c8fa653fcb5d95a6

**Comment by vmiklos** [comment]
Version 6.3 is now out with this in it.
