### ISSUE TITLE
FR : ability to rate & add info/comments to sleep items to better understand your sleep

### ISSUE THREAD

**Issue by GLLM** [vmiklos/plees-tracker#161]
Hi !

I'm trying to monitor my sleep, and your app being nice and FOSS, I've used it for some nights. I'm happy with it ! :)

My problem is that, after a few nights, I cannot remember if, when waking up in the morning, I felt fantastic, good, tired or wrecked !

There are a number of info I'd be willing to add/store with each sleep item:
- a rating of the night (i.e. wake up feeling with regards to the night) : with stars from 0 to 5 
- room temperature : a number
- food quantity : rating from 0 to 5
- moon phase : well, a moon phase

What would be lovely would be to be able to add more info to sleep items, to try detect patterns like : 
- sleep quality vs sleep length
- sleep quality vs bed time
- sleep quality vs food quantity
- sleep quality vs room temperature
- sleep quality vs moon phases
- sleep quality vs small awoken periods at night

As a MVP, simply adding & storing a sleep rating (from 0 to 5 stars) would be fine, so one is able to look it up afterwards. And make one's own stats/analysis.

As a V2, showing for each rating :  the average  bedtime, avg sleep length, avg room temp, avg moon phases, avg food quantity (1to5)  would be fantastic.

What do you think about this ?

Thanks
GLLM

**Comment by vmiklos** [comment]
Did you see that rating is already possible, just disabled by default? See https://github.com/vmiklos/plees-tracker/blob/master/doc/README.adoc#preferences-activity

**Comment by GLLM** [comment]
hi @vmiklos !
I'm kind of stupid, I did not see this :-/
However, I have feedback :
* only add the rating edition within the sleep item and show a read-only rating in the main screen. It will be less prone to user manipulation error.
* in the mainscreen, have the stars smaller
* i tried so check the graphs, annd could not graph rating & sleep length at the same time. Could this be feasible ? Same for rating vs. sleep duration.

My other suggestions remains ;-)

Thanks
GLLM

**Comment by vmiklos** [comment]
Let's try to focus on the rating itself here, ideally one issue is one request. :-)

I don't use the rating myself, so I don't have a strong opinion on that. The rating feature was added in https://github.com/vmiklos/plees-tracker/issues/28, @Narcolapser any opinion on the above? I.e. the request is to make the main activity rating widgets read-only, and only rate in the sleep activity. I'm a bit unsure, the current UI makes it easy to rate, which would be more complicated. On the other hand, it's currently confusing that a swipe results in a rate or on a sleep delete, depending on where you swipe, which is not ideal.

**Comment by GLLM** [comment]
Sure, on request at a time :)
I was giving you an insight on the whole idea !

**Comment by GLLM** [comment]
Can I help with the info needed @vmiklos ?
Is it end-user info, or dev info (for whihc, unfortunately, I wont be able to do much) !
thanks

**Comment by GLLM** [comment]
@vmiklos
> (...) The rating feature was added in #28, @Narcolapser any opinion on the above? I.e. the request is to make the main activity rating widgets read-only, and only rate in the sleep activity. I'm a bit unsure, the current UI makes it easy to rate, which would be more complicated. On the other hand, it's currently confusing that a swipe results in a rate or on a sleep delete, depending on where you swipe, which is not ideal.

I confirm, it happened to me this morning. I was swiping in my sleep items, and inadvertently put my finger on a star strip as I had to scroll quite a bit and boom : I changed a sleep item's rating.
I really think the rating should be readonly on the main screen ;)

**Comment by vmiklos** [comment]
Let's wait a week to see if @Narcolapser has anything to say. If we hear no opposition, then I can certainly go ahead with the rad-onlyness.

**Comment by Narcolapser** [comment]
It is indeed something I considered when you first implemented it for me. I was happy enough to get some one to do this for me for free that I didn't press the issue. But yes, the rating should be within the record and read only on the main screen. It would be nice if it pops up a little window asking how your slumber was when you clock out, but if I have to open the record just made to edit the score, I'm fine with that.

**Comment by GLLM** [comment]
Indeed, a small pop up appearing right after the user clocks out would be great !

**Comment by vmiklos** [comment]
Some find popups annoying, but making the rating bar read-only + move the editing of that to the sleep activity is certainly an option, I'll look at that.

**Comment by GLLM** [comment]
> Some find popups annoying, but making the rating bar read-only + move the editing of that to the sleep activity is certainly an option, I'll look at that.

Great ! I'd vote to use a bit smaller stars as well ;)

**Comment by vmiklos** [comment]
The above does the main -> read only, sleep -> read-write change + doc update.

Regarding the size of the stars, https://stackoverflow.com/questions/6153587/how-can-i-decrease-the-size-of-ratingbar seems to show how to do this, but I'm a bit hesitant to go with that, considering this really depends on the size of your finger... I bet there is a good reason why the default size is what it is.

Similarly for the popup, this can be somewhat annoying. Hopefully the zero stars is a good indicator that you need to rate that item, without disturbing you with an explicit interruption.
