### ISSUE TITLE
[Bug] Scrolling down in Statistics menu ends up showing an empty screen

### ISSUE THREAD

**Issue by GLLM** [vmiklos/plees-tracker#162]
Hi !
Using 7.1.4 on Android 9 (Samsung Galaxy S8+):

when I go to the Statistics menu, and I scroll down, then sleep statistics move up until the very last ... yet it continues to scroll and the screen is now blank of any statistics.
After this, I cannot scroll up to see again the statistics. I must exit this menu and go in again.

I do expect to the scrolling to stop when the last item is shown at the bottom of the screen.
A visual cue showing you cannot scroll more would be great.

Thanks
GLLM

**Comment by vmiklos** [comment]
Yes, I can reproduce the problem. @usashiki is this related to your changes in https://github.com/vmiklos/plees-tracker/issues/88 ?

**Comment by GLLM** [comment]
Fixed indeed. Thanks.
