### ISSUE TITLE
Negative sleep durations are possible

### ISSUE THREAD

**Issue by Brendan-McDonnell** [vmiklos/plees-tracker#178]
It is possible to change a past sleep to start after it began

**Reproducer steps**
1. Track some sleep
2. Tap on past sleep to enter detailed view
3. Tap on "Started on"
4. Change the starting date to the future

**Actual result**
Sleep with negative duration is accepted.
![image_1.jpg](https://user-images.githubusercontent.com/36059032/126597252-b8eae41a-e811-4e9a-8f3a-0945378e7146.jpg)

**Expected behavior**
Invalid sleep durations are not permitted

**Comment by vmiklos** [comment]
Good point. Should we just not update the timestamp or rather reset to 0 when a negative duration is requested?

**Comment by Brendan-McDonnell** [comment]
> Good point. Should we just not update the timestamp or rather reset to 0 when a negative duration is requested?

What about moving the other time? If the starting time is set to a time after the ending time, the ending time could be updates to match (duration of zero) and vice versa.

If it is possible to put input limits on the picker, that would also work, but it might get in the way of the user experience.

Some descriptive error could be best, too.

**Comment by vmiklos** [comment]
Hmm, it's hard to guess what is the intent when the duration would be negative (either the new start/stop date is incorrectly provided or you meant to adjust the other end first), so perhaps just refusing the edit with a clear error is the best.

Are you interested in looking into this yourself?

**Comment by Brendan-McDonnell** [comment]
I'm afraid I don't have time for another project until a few weeks from now at least, so I can't at the moment :(

**Comment by vmiklos** [comment]
That's fine. I'll comment here if I start investigating this, you can do the same, this way we can ensure there is no duplicated effort :-)

**Comment by vmiklos** [comment]
Finally got around to do this, will be also in a release early Oct.
