### ISSUE TITLE
Overlapped and blocked texts on main page

### ISSUE THREAD

**Issue by yuhuitech** [vmiklos/plees-tracker#184]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the main page, **some texts can not be seen fully and some texts overlap with each other**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 7.1.5, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that the texts on the main page could be seen fully and without overlapping.

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time, and then click "start" and "stop" for a couple of times.
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129579838-f8e825c4-06ac-4213-a60f-ece24dfd5010.png" alt="copy" width="250"/>

**Environment**

1. Version of plees-tracker : 7.1.5,
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by vmiklos** [comment]
Thanks a lot for the report & the PR! I have the same device, but haven't tested with a non-default font size, good catch. :-) Will review the patch shortly, please give a bit of time for me to do so.

**Comment by vmiklos** [comment]
The PR is now in and fixes the problem, I think. Thanks again for your contribution
