### ISSUE TITLE
24h time picker

### ISSUE THREAD

**Issue by SebiderSushi** [vmiklos/plees-tracker#19]
For users of 24h time format, a 24h time picker would be preferred.
I'm not familiar with specific implementations, but for example the [LineageOS Clock](https://github.com/LineageOS/android_packages_apps_DeskClock)  application or [Etar Calendar](https://github.com/Etar-Group/Etar-Calendar)  on F-Droid feature 24h time pickers.

They present a regular 12 hour clock face with a second, smaller inner circle of continued numbers that count beyond 12 hours.

**Comment by vmiklos** [comment]
Agreed, we should act based on locale or just default to 24h picker. My Pixel clock app with en-US locale also offers a 24-hour picker, probably both that and the LineageOS clock is based on the AOSP DeskClock.git code.

**Comment by vmiklos** [comment]
I bet this will be trivial to fix as well:

https://developer.android.com/reference/android/app/TimePickerDialog

And then this `false`:

https://github.com/vmiklos/plees-tracker/blob/979d76574d121f49e556e763a1c353236f214f76/app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt#L58

Is exactly that 24 hours view bool.

**Comment by vmiklos** [comment]
This is good enough for now, I think. If someone will need the old 12h behavior, we can add a setting.

**Comment by vmiklos** [comment]
Version 6.3 is now out with this in it.
