### ISSUE TITLE
Allow the user to manually edit an entry

### ISSUE THREAD

**Issue by shadow00** [vmiklos/plees-tracker#2]
Sometimes I forget to press start before falling asleep, and manually editing unix timestamps in a csv file is kind of a pain. I suggest creating a date and time editor for the start/stop times of an entry, so that a user could tap/long press an entry and manually adjust it, without having to export a file, do math with unix timestamps, and import the file again.

**Comment by vmiklos** [comment]
I went for a 2-step UI: first you can tap on a sleep to open a new activity, then there you can tap on the start or the stop date and tweak the date and time. The main activity still has to be updated as it assumes sleeps are not mutable. But other than this, it works. I'll dogfood this a bit more during the weekend, then plan to cut a v5.0 release, so you can try it out as well. :-)

**Comment by vmiklos** [comment]
Will release v5.0 soon, this now works on master.

**Comment by shadow00** [comment]
Awesome! Can't wait to try it out!

**Comment by shadow00** [comment]
By the way, you might want to add this feature in the app description as well. I'd make a PR myself, but I'm kind of swamped for the next few days :/ Still, thank you very much for taking the time to implement this!

**Comment by vmiklos** [comment]
cf5012bcb61f457197fb80dd5419fe9e47ac5f9a mentions it now

**Comment by vmiklos** [comment]
Build will be at <https://f-droid.org/repo/hu.vmiklos.plees_tracker_5.apk> once it's done.

**Comment by vmiklos** [comment]
It's now there.

**Comment by shadow00** [comment]
Just gave it a try - it works great!
