### ISSUE TITLE
Chronological order of list not enforced

### ISSUE THREAD

**Issue by SebiderSushi** [vmiklos/plees-tracker#20]
Modifying the times of a sleep entry can produce an entry listing with non chronological order.

I'd propose sorting the list by start time to make sure everything stays sorted.

**Comment by vmiklos** [comment]
Every sleep has its ID (simple auto-increment integer) and we currently sort using that, see here:

https://github.com/vmiklos/plees-tracker/blob/9252f9c2f17c9207252c665540cbdc02561d4233/app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt#L23-L24

You could tweak this to sort by start time instead, just need to change the SQL query. Are you interested in doing this yourself and sending a pull request?

**Comment by SebiderSushi** [comment]
oh kotlin nice
But it would be just a one line change right? Or are there any tests that need to be changed as well?

While it's true that i've already made some one-line change Pull Requests its still weird going all the way of a PR for that...

**Comment by vmiklos** [comment]
> But it would be just a one line change right?

Correct. :-) Just clone the repo, do the change, test that it does what is the intention, create a PR. Ideal for a first patch!

**Comment by SebiderSushi** [comment]
Seems like you've lured me in successfully :)
Sorry that it took me so long and that i just did it out of nowhere. But given the impact and size of the change i guess this doesn't hurt much anyway.

**Comment by vmiklos** [comment]
Version 6.3 is now out with this in it.
