### ISSUE TITLE
Importing entries from the calendar creates duplicates

### ISSUE THREAD

**Issue by gAQeNQ** [vmiklos/plees-tracker#207]
**Reproducer steps**
1. Log some sleeps
2. Export them to calendar
3. Import them back
4. There are duplicitie

**Actual result**
There are duplicitie

**Expected behavior**
No duplicities

The issue is related to https://github.com/vmiklos/plees-tracker/issues/150 which was solving the export duplication problem.

**Comment by vmiklos** [comment]
Yes, this makes sense to me, again need to remember a timestamp to do incremental imports.

**Comment by vmiklos** [comment]
I'll cut a v7.2.4 release in about 2 weeks that will contain this fix (if you use the fdroid builds).
