### ISSUE TITLE
UI: When Awake Duration is ON -> It's hard to see where one entry ends and another begins

### ISSUE THREAD

**Issue by gAQeNQ** [vmiklos/plees-tracker#208]
**Reproducer steps**
1. Log few entries
2. Set "Show awake duration" to ON

**Actual result**
![image](https://user-images.githubusercontent.com/84355256/140608020-ffb1174a-df86-4b12-8ca6-bff14c60782f.png)

**Expected behavior**
Some UI element (spacing/separator) would be great to visually separate the logs. Maybe even to get creative and add some UI element containing awake-for.

```
[  Start     ..... ]
[  End       ..... ]
[  Duration  ..... ]
                                          <---- spacing
--- Awake time inside separator ----
                                          <---- spacing
[  Start     ..... ]
[  End       ..... ]
[  Duration  ..... ]
```

**Comment by vmiklos** [comment]
These are cards, one card / sleep. But some spacing or border makes sense.

**Comment by vmiklos** [comment]
https://stackoverflow.com/questions/24618829/how-to-add-dividers-and-spaces-between-items-in-recyclerview seems to be an approach that can be used here.

**Comment by vmiklos** [comment]
If you don't build from source, this should be in the next release in early 2022-01.
