### ISSUE TITLE
"Daily" stat seems to omit 0-sleep days when averaging

### ISSUE THREAD

**Issue by SebiderSushi** [vmiklos/plees-tracker#21]
I am curious about "how much sleep time do i have per day on average?".
I maintain extremely irregular sleeping habits that can include days with absolutely no sleep at all. In this case, an average stat that takes these days into account is required.

However, this let's me acknowledge 3 valid stats:

- Average sleep duration (current average stat)
- Average sleep on days with sleep (current daily stat?)
This is relevant to answer "How long are my sleep sessions on average?" with multiple sleeps a day. It is not entirely accurate but grouping sleeps per day looks like a simple definition for "sleep session" that still makes sense.
- Average sleep duration per day
The use case i described in this issue

**Comment by vmiklos** [comment]
I think the daily stat can be improved to take "empty" days into account, and then we can still have just two time duration on the main screen.

**Comment by vmiklos** [comment]
Done, though it may time till it gets past CI, given that https://www.githubstatus.com/ is not green.

**Comment by vmiklos** [comment]
Now fixed.

**Comment by vmiklos** [comment]
Version 6.3 is now out with this in it.
