### ISSUE TITLE
Implementing opportunity to make notes for each sleep

### ISSUE THREAD

**Issue by MojoDodo** [vmiklos/plees-tracker#239]
At the moment there is an option to rate each sleep using a scale of 5 stars.
It would be nice to also have the possibility to add text notes for each sleep.
Thanks in advance and best regards
Mojo

**Comment by vmiklos** [comment]
Hm, what do you have in mind exactly? For example, there could be an additional single-line, plain text comment field for each sleep on the sleep activity. Would that be enough?

**Comment by MojoDodo** [comment]
Well, one could of course devise fancy features, but as I understand Plees Tracker is meant to be kept pretty simple. So yes, I think a simple plain text field would do the job.

Thank you for the nice app and for considering implementing such a feature!

**Comment by vmiklos** [comment]
OK, that makes sense. Still need to use a proper CSV reader/writer first, as at least allowing "," in that plain text field is a reasonable request. :-)

**Comment by vmiklos** [comment]
This will be in v7.3.0, to be released early Feb -- unless you already build from sources yourself. :-)
