### ISSUE TITLE
Start and stop button on dark theme

### ISSUE THREAD

**Issue by Yaxsh** [vmiklos/plees-tracker#27]
The button for starting and stopping a sleep cycle is too hard to notice in the dark theme of the app. I've included a screenshot to demonstrate it. Perhaps it would be useful to add some sort of outline of the button to better illustrate it and make it for noticeable in the next update.

![plees-tracker-dark](https://user-images.githubusercontent.com/37214100/85730105-ab94f780-b6f9-11ea-82a3-35d1ddb02afb.jpg)

**Comment by vmiklos** [comment]
Yes, that's indeed poor. Are you interested in looking at this yourself? It's possible you can style the floating action button just by tweaking the XML file, see app/src/main/res/layout/activity_main.xml:114.

**Comment by vmiklos** [comment]
The FAB background is blue-ish (start) and red-ish (stop) in non-dark mode, but it was black in dark mode. Now the non-dark mode is unchanged, but the dark mode has it as gray-ish. I think this was just an accident, the intention was to get rid of the purple background in the app bar and this was a side effect.

**Comment by vmiklos** [comment]
Fixed on master, will probably do a release next week.
