### ISSUE TITLE
Add a start time offset

### ISSUE THREAD

**Issue by GitFincy** [vmiklos/plees-tracker#274]
No one falls asleep right as they press 'Start'. An option to add a start time offset would be neat. Could just be pre made values like 5, 10, 15 minutes or an exact value input (in minutes).

Wanted to try and implement this myself, but I unforunately have 0 experience with android applications.

**Comment by vmiklos** [comment]
The settings activity already has a time selector for the ideal sleep length, something similar could be added for a length that's always added to the actual start timestamp, reducing the sleep length.

**Comment by vmiklos** [comment]
Will be available in v7.4.0, to be released in early Aug.

**Comment by k3dar** [comment]
Can you please add more values? 30/45/60minutes?

**Comment by fincentxyz** [comment]
> Can you please add more values? 30/45/60minutes?

Haha, I also wish for more values sometimes. Some nights I have to restart the sleep tracking because I'm not able to fall asleep in 15 minutes.

Maybe it would be nice to be able to select a number for the minutes ourselves with some sort of number picker.

**Comment by vmiklos** [comment]
> Can you please add more values? 30/45/60minutes?

Sure, why not. Care to submit a PR? If not, I'll get around to do that.

> Maybe it would be nice to be able to select a number for the minutes ourselves with some sort of number picker.

That's also doable, could you please open a new issue for that? This is closed already. Thanks.
