### ISSUE TITLE
A new icon for 'Awake for'

### ISSUE THREAD

**Issue by GitFincy** [vmiklos/plees-tracker#275]
This is a really minor enhancement, but different icon for the 'Awake for' data point would be nice. Currently it's the exact same as the 'Started on icon'.

**Comment by vmiklos** [comment]
Are you interested in fixing this yourself? See the end of `doc/README.adoc` for the source of the existing icons, hopefully you can find some icon that looks good on the same site. Then you just need to refer to it from the relevant .xml file, I don't think code changes are needed to fix this issue.

**Comment by GitFincy** [comment]
Definitely! I'll look into it this week. Thank you for creating plees tracker!

**Comment by GitFincy** [comment]
Hey, I don't have Android Studio and therefore also no access to Vector Asset Studio to convert an image to a vectorized asset. I found some websites that convert a png to a vectorized image and xml, but I didn't think they looked good enough.

The icons I considered using were either:
A clock icon: https://www.flaticon.com/free-icon/time_25692
Or an open eye icon: https://www.flaticon.com/free-icon/eye-open_25186

**Comment by vmiklos** [comment]
![image](https://user-images.githubusercontent.com/13838/194648973-f29eccaa-c091-4f75-bf44-75541162e754.png)

Something like this? Probably good enough, but feel free to nitpick on the actual icon / color.

**Comment by GitFincy** [comment]
Looks good to me. Thank you for implementing both of my suggestions, keep up the great work!
