### ISSUE TITLE
[Feature Request] allow multi-line notes, extend #239

### ISSUE THREAD

**Issue by ijgnd** [vmiklos/plees-tracker#277]
Thanks for making this app.

I suggest to extend the feature requst #239: In the Sleep Details view for one night I suggest to expand the Notes section from one line to some kind of text box so that I can read longer texts I entered.

I don't think that linebreaks in such notes are needed. I can imagine, that handling linebreaks might compliate the csv export and so on.

There's a lot of blank space at the bottom of the screen, so that e.g. a five-line box should fit well.

I think this still fits to a simple sleep tracker and is not feature creep. For me it's very useful to take longer notes, e.g. if, when, and why I woke up during the night, how tired I was after getting up (which is not always related to how well or long I slept), and some things that might influence the sleep quality from the evening before like exercise, watching TV, etc.

There are a lot of other apps that allow to exactly quantitavely track such other stuff. But that's too much for me and it's complicated to use two apps. I assume for a lot of people it's sufficient to have some qualitative notes to find out some big factors that influence their sleep. Or maybe other people want to capture some notes about dreams in the app they already use and that respects their privacy.

**Comment by vmiklos** [comment]
plees-tracker uses commons-csv to import/export CSV files, https://stackoverflow.com/questions/39653399/apache-commons-csv-parse-record-with-new-line-chars says that multiline strings are not a problem. So adding this is probably reasonably straightforward.

**Comment by ijgnd** [comment]
Thank you very much for implementing this feature! And thanks for doing it so quickly.
