### ISSUE TITLE
Add changelog (release notes) to F-Droid metadata

### ISSUE THREAD

**Issue by Gitoffthelawn** [vmiklos/plees-tracker#281]
A link to the changelog is missing from the F-Droid metadata.

Could you add it, so the changelog can be quickly accessed via the F-Droid website and app?

Thanks for the helpful tool!

**Comment by vmiklos** [comment]
Sure, can do that, just need to figure out what is the syntax to do so. :-)

There are two ways to have metadata (fast lane and something else), do you know an other app that links its changelog and uses the same markup as plees-tracker?

Thanks.

**Comment by Gitoffthelawn** [comment]
Thanks.  AFAIK (and I might be mistaken, so please confirm!), you just provide a link in the metadata.  If the user clicks the link, the client will have to figure out how to render it.

Most people choose to use markdown or a plain text file for their changelogs.

**Comment by vmiklos** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11060

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by vmiklos** [comment]
The above is now merged.
