### ISSUE TITLE
Consider lowering required API level

### ISSUE THREAD

**Issue by Gitoffthelawn** [vmiklos/plees-tracker#282]
I've been stuck on an old version of this app because new versions now require API 24.  As you know, that means ~20% of Android devices (which is tens of millions of devices) cannot use the current version of this app.

Personally, I repurpose an old Android device as my "sleep device".

What would be lost by changing the minimum required API to a level that would allow this helpful app to work with at least 95% of Android devices that are in use?  If 95% isn't a reasonable goal, what about ~90%?

**Comment by vmiklos** [comment]
What is the API level that you would want? plees-tracker went from 22 to 24 to show the timezone of sleep start/ends, perhaps we can make that conditional and lower the API level. It would be a bit confusing if your country does DST (on those 2 nights every year), but it would be usable.

**Comment by vmiklos** [comment]
@Gitoffthelawn ping, do you need API level 23 or 22?

**Comment by Gitoffthelawn** [comment]
Thanks for your ping, and I'm very sorry for the long delay.  I'm working though a few hundred notifications.  Such fun!

API level 16 or 17 is ideal to work with older devices, but API level 23 will handle the device I currently use to track sleep.

I suppose for regions with DST, you could allow users to manually enter the transition dates if the API doesn't support providing them.

BTW, do you know how Android handles the situation when regulations change DST for specific regions?  For example, let's say a device uses API 28 and no longer gets updates.  Then let's say a user lives in a region that has DST.  Then the regulations change so that DST is removed for the region.  Does the Android device somehow know about this change, or is it forever "broken"?

**Comment by vmiklos** [comment]
> API level 16 or 17 is ideal to work with older devices, but API level 23 will handle the device I currently use to track sleep.

OK, will try to lower to API level 23 with some Android-style ifdefs.

> BTW, do you know how Android handles the situation when regulations change DST for specific regions?

I expect that if you don't run an Android version that gets security updates, then you won't get timezone updates, either. But best to ask on some Android developer forum. :-)
