### ISSUE TITLE
Feature: Calendar Integration as visualisation and form of backup

### ISSUE THREAD

**Issue by petrhejna** [vmiklos/plees-tracker#29]
Thank you for awesome FOSS app! 😍 

I like to propose a feature to allow integration with standart Android calendar.

This has multiple benefits:
- Allow visualisation of sleep interval withou need to actually code it.
- Adds backup out of the box (calendar can be synced by different app like EteSync or in privicy worst scenario by Google).

-----

Btw, do you have BTC donation address? I may want to add it into README.md 😼

**Comment by vmiklos** [comment]
How would this work, once you finish sleep, you create an entry in the calendar after-the-fact? It seems to be a bit noisy, but if it's opt-in, it could work.

No, at the moment this project is a free time hobby, so if you would like to donate to help FOSS projects, donate it to some other project which needs financial help.

**Comment by petrhejna** [comment]
I thought about scenario like this:

1. Select to which calendar it syncs in settings.
2. If there are some entries named "Sleep <ID>" they are imported as sleep records.
3. After the sleep recoring is finished, new entry is automatically created to the calendar.
4. Edit of the time is propagated to the calendar.
5. Deleting entry will remove it from calendar.

----

About donation: I have donated to all FOSS apps from F-Droid I use, because I believe the alternative to Google-Orwellian-Mobile-Wold has to be created and maintained.

**Comment by vmiklos** [comment]
> I thought about scenario like this:

Ah great, that sounds reasonable to me. You have to select which calendar to import to, which makes this implicitly opt-in. (So if somebody doesn't want this, it's not spamming.)

Are you interested in looking at this yourself?

**Comment by petrhejna** [comment]
> Are you interested in looking at this yourself?

If this means testing I would love to.

If its about develipment, I have no experience with mobile development not Kotlin.

**Comment by vmiklos** [comment]
OK. :-) I can probably look into this at some stage.

**Comment by ed-george** [comment]
As mentioned, I am happy to look at this 👍 

Will follow the general guidelines set out in this request

- List available calendars
- User selects a calendar to import from
- Import records matching Sleep from user-defined calendar

I have already made a start on this, will make an early PR for review tomorrow ✨🙏

**Comment by vmiklos** [comment]
Unfortunately this issues is now hijacked, as the PR above implements import from calendar, while what you requested is an export to calendar. ;-)

I'm trying to have a 1 issue, 1 PR relationship, do you you think you could file a follow-up issue to do the export side as well at some stage?

**Comment by petrhejna** [comment]
No problem. I did. ;) thanks a lot
