### ISSUE TITLE
Sleep data prior to 2022-08-16 vanished / disappears in `0.7.4`

### ISSUE THREAD

**Issue by kraftnix** [vmiklos/plees-tracker#310]
**Reproducer steps**
1. (optional) have many months of sleep data
2. install/upgrade to `0.7.4` (F-Droid)
3. (optional) if install was fresh, try add a sleep data point with a date prior to `2022-08-16`

**Actual result**
Any sleep data before `2022-08-16` does not appear in main screen, nor any stats or graphs.

**Expected behavior**
Sleep data should be present as usual.

**Extra Notes:**
 - I tried restoring an older backup into the app (from an old phone), received an error message `File version could not be synced...` (couldn't catch it all since it only appeared briefly).
 - I updated my old phone with pre-`2022-08-16` data in it and it is empty / shows no data. I then reverted the app version to `0.7.3` and re-imported it's own backup, and the data showed up again.
 - On trying to add an sleep event in the past (pre-`2022-8-16`), the data will not appear, _however_ it seems new sleeps are still tracked with the same `Sleep #nnn` number, while my app only shows 7 data points, the Sleep # is in the hundreds (as it should be).
 - I backed up data again after upgrading to `0.7.4` where the pre-`2022-8-16` data has disappeared, and all the data is still present in the `backup.csv`, so it appears that **no data loss has occurred**, which is good.

**Comment by vmiklos** [comment]
Hm, 2022-08-16 was about a week ago, is this just a matter of going to the settings activity and then setting dashboard -> duration to something other than "last week"?

**Comment by kraftnix** [comment]
You are right, the duration was set to "last week". Perhaps the update changed it since I don't remember changing the option myself.

Thanks for the quick find! (I saw this shortly after you replied but forgot to reply here)
