### ISSUE TITLE
[Feature Request] Set to app to create automatic exports for backups 

### ISSUE THREAD

**Issue by TobiasDev** [vmiklos/plees-tracker#32]
Hello,

I use this app to track my sleep and love it so far. It has everything I need regarding features to track my sleep. The only thing I would like to ask if it would be possible to set an automatic export of data once every day or week? 

The reason for this is that I could then tell my NextCloud app to always upload all data from the backup folder when I'm on WIFI. This way if I lose my phone (and haven't manually exported the data in a while) I would still have an automatic backup.

**Comment by vmiklos** [comment]
Makes sense. I guess doing this weekly would make sense, with the ability to set a higher frequency. And probably we can avoid a timer, just do the export in case we just finished sleeping and there is no export yet for the current week.

Are you interested in looking at this yourself? Probably not hyper complex to add, the export code is already there.

**Comment by vmiklos** [comment]
Do you have any other open source app that has such a feature already? I'm asking as I guess the trick here is to get permanent access to a nextcloud folder. Normally nextcloud is a storage provider, so if I select a folder, I may easily get some URL which is working right after a selection, but not after restarting the app.

Seeing how others do this kind of thing would help avoiding such pitfalls.

**Comment by TobiasDev** [comment]
Sorry, for the late answer! I missed this. I don't believe I would be able to implement anything like this, since I never worked in Java before. :( Sorry. 

And I actually didn't mean that the app should export directly to NextCloud. :) That I haven't actually seen (except for something that syncs like Joplin Noteapp), but that is a different feature. 

The NextCloud Android app has a feature that you can tell it that anything that is stored inside a certain folder should be synced to the cloud when you have wifi. So basically if the app exports a csv, xml or whatever backup format you use. I can tell the NextCloud app to look in that folder when I'm on Wifi and upload anything inside. :)

**Comment by vmiklos** [comment]
Ah OK, storing to just a dir on the "sd card" is easier, great.

**Comment by zaheernathani** [comment]
Yes, we need an auto export option at a particular location

**Comment by vmiklos** [comment]
You can now test this if you build from source. I plan to cut a next 7.0.5 release early Jan if you prefer taking the app from fdroid.
