### ISSUE TITLE
[Suggestion] allow modification of sleep times

### ISSUE THREAD

**Issue by fabmazz** [vmiklos/plees-tracker#330]
I was looking for a sleep tracking app, and I found this one on F-Droid.
The basic functionality is good, but this morning I forgot to go into the app and set that I woke up, and now the sleep time is wrong and I can't correct it.
Could it be possibile to modify the times of sleeping? 

Also, I was fiddling around the first day, and I tried to start and stop the sleep function. Now I have one sleep logged of 0 minutes, and the average sleep times calculated is off because of it.
Could you add the possibility to remove one sleep? It seems to me that now I can only delete everything, which I don't want to.

Thanks for the app anyway :) it looks quite good

**Comment by vmiklos** [comment]
Possibly you missed that the app has documentation:

https://github.com/vmiklos/plees-tracker/tree/2356e8b33ddb62adf4d78f56ff8103515cc41665/doc

You can tap on the sleep item to edit the start/stop date. And yes, swiping can delete it.

E.g. the gmail app does the same swiping to delete emails, there is even a hint that it'll delete the sleep, a red background + trash icon is shown as the swipe is started. Same is there in nextcloud notes, so it feels like this is pretty standard.

But still, are you aware of an app that has a better hint, we can consider following that as an example?

**Comment by vmiklos** [comment]
> Or rather, a button in the menu liking to the documentation/how to :)

I like this option the most. Somehow I need to merge the website and the documentation into one coherent piece and link to that from the app. Will do.

**Comment by vmiklos** [comment]
Hmm, also https://developer.android.com/training/tv/playback/onboarding looks helpful, for those who would never read documentation :-)

**Comment by fabmazz** [comment]
Yes, having an introduction on first app opening would be wonderful. But I
understand that is a bit more work :-)

Il giorno sab 29 ott 2022 alle ore 19:16 Miklos Vajna <
***@***.***> ha scritto:

**Comment by vmiklos** [comment]
Looks like this:

![image](https://user-images.githubusercontent.com/13838/200081018-44afbfbc-4bf7-404d-86ad-68c029c3b518.png)
