### ISSUE TITLE
[Feature request] Option to include graphs based on day vs hours slept

### ISSUE THREAD

**Issue by NinjaGobbler** [vmiklos/plees-tracker#358]
Amazing app, thanks for creating this. The app already has pretty impressive graphs and additionally, I was thinking to have one feature that will be helpful. 

Day wise trends, I mean day vs number of hours on X and Y axis respectively. This way, I can look for trends and understand if on certain days my sleep schedule is being altered. For example, maybe Friday nights I might tend to sleep late or Wednesday nights somehow due to my work schedule it tends to be delayed,  or Sunday night my sleep decreases due to late night and early Monday etc.

It's not critical, but it definitely helps to have this in the long run when I see it 6 months down the line, it could give me some interesting insights using which I could be more conscious and alter my schedule accordingly to make it productive.

**Comment by vmiklos** [comment]
Hmm, currently each graph is just one metric, where here you would want a graph that can be parameterized for each day of the week.

The other complexity is that the title wants the sleep duration, but in your comment you also mention the sleep start to be interesting.

As a first cut, we have a graph for the start time but not for the stop time. Would that be useful to add? Then we can get to the more tricky graphs.
