### ISSUE TITLE
Unable to find the Toggle Widget on Android

### ISSUE THREAD

**Issue by NinjaGobbler** [vmiklos/plees-tracker#359]
As per the documentation mentioned below, we can add a toggle widget to home screen.
https://vmiklos.hu/plees-tracker/usage.html#toggle-widget

But I am unable to find that option in the Settings within the app. Even from Android home screen, I couldn't find any widget from Plees tracker app.

Maybe I am missing something here :)

**Comment by vmiklos** [comment]
Hmm, seems it's there for me. When I just long press on some empty area on my home screen, I get this:

![image](https://user-images.githubusercontent.com/13838/218190069-1a75ef20-b532-4a7e-bd7c-df35a7e7ea29.png)

Don't you get the same?

**Comment by NinjaGobbler** [comment]
@vmiklos I do find the widget but once its added to my homescreen, if I tap on it the app just opens and timer does not toggle (start or stop).

I am expecting this button to act as a toggle button where inatead of opening the app and selecting start timer / stop timer, i can just toggle them from homescreen but that's not how its behaving for me.

Please let me know if I am missing something here.

**Comment by vmiklos** [comment]
It's valid to expect toggle behavior, I think it used to work like that in the past. I'll take a look.

**Comment by vmiklos** [comment]
Now works for me on Android 12, there was also an other inconsistency I found how the quick settings tile launched the activity (and the flag was missing in the widget case).

**Comment by NinjaGobbler** [comment]
Thank you @vmiklos for fixing this. By the way, if I want to incorporate this fix into my currently installed application version, how do I do that? 

Or should I probably wait until next release where current commits will be pushed?

**Comment by vmiklos** [comment]
What do you have installed currently, self-built binary, apk from github actions or fdroid?

**Comment by NinjaGobbler** [comment]
I have it downloaded and installed from f-droid.

**Comment by vmiklos** [comment]
I'll cut a new release later this week, it'll get into f-droid soon.
