### ISSUE TITLE
Bug: Broken Awake for, slept for

### ISSUE THREAD

**Issue by Disaster2life** [vmiklos/plees-tracker#361]
**Reproducer steps**
1. start and stop the timer for a second to record a past entry
2. Adjust time to the hours slept
3. Numbers are now broken

**Actual result**
The numbers for Slept for, and Awake for, are broken, diaplaying 28:38, and -18:-3 respectively 

**Expected behavior**
show non broken sleep lenght and awake for timings ![Screenshot_2023-02-25-01-41-37-43_e34ec1b80098235c547be5bc9e5ad05e.jpg](https://user-images.githubusercontent.com/19931889/221281585-8106e1e9-f174-41fa-9b54-1f7cd180e704.jpg)

**Comment by vmiklos** [comment]
Hm, the "slept for" looks OK, the start is 24th and the stop is 25th, so >24 is expected, and the actual diff looks correct.

What would you expect there?

**Comment by Disaster2life** [comment]
Ah apologizes, I didn't see the different dates, I messed up while applying the dates and didn't notice, my bad, apolgoies
