### ISSUE TITLE
Better averages

### ISSUE THREAD

**Issue by girlmaya** [vmiklos/plees-tracker#366]
Both the per-sleep average and daily average become unhelpful to me. This is because 1. some nights I wake up and record that before sleeping more, and 2. I dont record sleep of every night because I forget.

I dont have any strong ideas here for a solution here but i would appreciate if you could look into it, thanks

**Comment by vmiklos** [comment]
Perhaps have a mode that is like the 'average of daily sums', but ignores days where the sum is 0, assuming you simply forgot to track on those days?

**Comment by girlmaya** [comment]
Sure, i would be satisfied with that

**Comment by foss-** [comment]
Just noticed this. The daily average is not informative and actually false in its current implementation. I don't track sleep every day. And in my case of the 4 days I tracked last month this comes down to an average lf 1 hour of sleep per day.

While this is mathematically correct, it certainly is not helpful to the user.

A better way to handle this is to simply calculate the daily average from the nights where sleep was actually tracked and ignore the days, where no tracking occured for the calculation of daily average.

**Comment by vmiklos** [comment]
If you sleep once a day, this use-case works already, see the settings. You probably want to enable "show average of sleep durations" and disable "show average of daily sums". Can you try if that does what you need? :-)

This issue is about a third use-case, where you sleep multiple times a day, but you sometimes forget to record an entire day.

**Comment by foss-** [comment]
Got it, thank you. Wouldn't it make sense to show that average by default? I think most users lack discipline to track *every* single night. And sorry for asking in the wrong issue.

**Comment by vmiklos** [comment]
The current default was introduced to address #308. If you want to change it, I would suggest to start a discussion thread, involve the reporter of that issue and see how things can be improved for everyone.

I don't care too much either way, except that changing defaults like a flip-flop probably makes everyone angry. :-)

And yes, best to keep this issue focused on the original problem description, which is about ignoring 0 lengths in the "average of daily sums" calculation.

**Comment by vmiklos** [comment]
Great, this can be literally turned into a unit test. :-)

**Comment by vmiklos** [comment]
Will be in the next monthly release.
