### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by rohitzerofour** [vmiklos/plees-tracker#370]
Can you guys add a feature like if i forgot to press the start before sleep so if i have some option to manually enter the start and end time also will be great.

**Comment by vmiklos** [comment]
You can start a sleep, stop it immediately, then tap on the sleep item and there you can edit both the start and end date. See here:

https://vmiklos.hu/plees-tracker/usage.html#sleep-activity

Does that help?

**Comment by rohitzerofour** [comment]
Yes, that worked. Thanks for the app
