### ISSUE TITLE
Sleep variance and standard deviation

### ISSUE THREAD

**Issue by Lastaapps** [vmiklos/plees-tracker#388]
Hi, I find the average daily sleep stats quite interesting, but I thing they are not representative enough for people with "broken" sleep schedule.

For example I sometimes sleep ~6h and somethimes ~9h, which averages to nice 7.5 h. But the mean value of sleeps does not represent these differences. Therefore I would suggest adding standard deviation or variation into the mix. I suggest updating the design like this, maybe using % instead of the time as time diff can confuse somebody. Also this is only useful for daily average, not sleep average as a small nap would make this totally irrelevant.
Thanks for the app!

![Screenshot_20230527-093451_Plees Tracker.png](https://github.com/vmiklos/plees-tracker/assets/47794319/b5f68e0f-e48b-4498-b44e-5618cd005310)

**Comment by RageGamerBoi** [comment]
I suggest taking a look at the solutions posed in #366 as well.

**Comment by Lastaapps** [comment]
I looked at it before posting this. As I understand it, the issue solves the problem of people not tracking their sleep every day. But my suggestion is (after the empty days get thrown away) to show more statistical data about sleep during the tracked days.

The Length graph shows in fact what I want - how much the lengths differ from the average. But it would be nice to see this in a numeric way on the home page so I can track how my schedule improves/worsens over time.

**Comment by RageGamerBoi** [comment]
Ah, ok. That makes sense, and I like that idea.
Sorry for not understanding at first.

**Comment by vmiklos** [comment]
I think the idea makes sense, we just need to figure out how to show this while keeping the UI clean. What about showing this only when the "compact view" is disabled? (That currently shows seconds and timezone.)

Also, are you interested in adding this yourself?

**Comment by Lastaapps** [comment]
Currently, my examination period is ongoing so not now. Then I may look at it, but I'm not sure if I want to learn a whole new codebase 🤔. Eh, screw it, I'll try to, but this issue will have to stay open for a while.

As for the design, the "Compact" view affects individual items only as far as I know, because of that I would rather add a new switch.

**Comment by vmiklos** [comment]
A dedicated new setting is also fine, the idea was to make this opt-in somehow, so you can have it, but it doesn't clutter the default UI.

**Comment by vmiklos** [comment]
Coming back to this, perhaps the cleanest is to add variation as a chart type in graphs activity. And it could work with the daily sums, so a little nap does not increase variation.

**Comment by Lastaapps** [comment]
Hi, sorry for inactivity, I was much busier than I expected in July.

Totally agree it should work with daily sums.

And I'm not sure variance can be shown in a graph, as it is the property of a whole dataset (week, month, year, ...), not only a single data point (day).

What we can show is a graph with the sleep length average and daily differences + somehow highlight the standard deviation bar/area around the average. But I don't think this would be as useful as the current sleep length graph covers it.

**Comment by Lastaapps** [comment]
I get what you meat with the graph (how can it be make sense) and I'll try to do it like this, forking the project now! (finally, sorry for the huge delay).
