### ISSUE TITLE
Fall Asleep Delay

### ISSUE THREAD

**Issue by RageGamerBoi** [vmiklos/plees-tracker#390]
A fall asleep delay/timer would be handy for people who don't immediately fall asleep after starting tracking.
The delay could be adjustable somewhere as well, but it doesn't have to be.

**Comment by vmiklos** [comment]
Settings -> Start time delay is a setting for this, did you find that?

**Comment by RageGamerBoi** [comment]
Oh... thank you :)
Maybe it should allow longer times, but I'm glad it's already there.

**Comment by vmiklos** [comment]
Sounds like the existing setting does what you want.
