### ISSUE TITLE
NetworkOnMainThreadException while importing data from exported csv file (ArrowOS)

### ISSUE THREAD

**Issue by foss-** [vmiklos/plees-tracker#407]
**Reproducer steps**
1. … > Export to File
2. Import File > Select exported csv file on second device

**Actual result**
While Plees Tracker shows `Import finished successfully` the visible sleeps don't change. A few nights were already tracked on the device the import is attempted on, but those never vanish nor is older data added.

**Expected behavior**
The import should ideally add data to the existing data or if that is not possible remove the current data and replace it with the imported data. In the latter case a warning dialog should ask users how to proceed.

Android 13.1
Plees Tracker 7.6.0 (46)

**Comment by vmiklos** [comment]
Just to be clear, the problem only happens when you already have sleeps and you try to import, is that correct?

**Comment by foss-** [comment]
To verify I did the following: with a few entries still there I again tried the import and that did not work. I got the success message but the imported sleeps never showed.

Then I used `… > Delete All Sleep`, confirmed with Yes, but Import from File still has the same result: success message but no sleeps show. This is persisting after closing and re-opening the app.

**Comment by vmiklos** [comment]
Hm, both scenarios work for me on a Pixel 6a, also on Android 13. I'll try to see if perhaps a clean emulator state allows reproducing.

**Comment by foss-** [comment]
This is ArrowOS 13.1(TQ3A.230705.001) on lisa device. Right, my attempt to import in the end was to import form plees-tracker.csv stored on phone storage not nextcloud, to make sure the potential permission problem is not at play.

**Comment by vmiklos** [comment]
adb logcat reports (sanitized):

```
java.io.FileNotFoundException: Failed to open document for writing plees-tracker.csv
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1562)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1537)
        at hu.vmiklos.plees_tracker.DataModel.exportDataToFile(DataModel.kt:290)
        at hu.vmiklos.plees_tracker.DataModel$exportDataToFile$1.invokeSuspend(Unknown Source:18)
```

Now the question is why openOutputStream() throws an exception even after takePersistableUriPermission(FLAG_GRANT_WRITE_URI_PERMISSION) happily succeeds (i.e. doesn't throw a SecurityException).

The plan is to read some of the k9 mail code which reportedly works fine in this case; and probably need to figure out how to install this ArrowOS in an emulator to be able to reproduce & fix the problem locally.

**Comment by foss-** [comment]
Never tried that, quick search turns up https://stackoverflow.com/questions/25985384/run-custom-rom-on-android-emulator

Sounds like it is possible but since roms are device specific you'd need to emulate a device and then pick the corresponding download.

**Comment by foss-** [comment]
Importing with blank plees-tracker worked.
Importing with existing past sleeps results in app crash. Logcat sent via email.

**Comment by vmiklos** [comment]
Oh, this is interesting:

```
E AndroidRuntime: android.os.NetworkOnMainThreadException
E AndroidRuntime:       at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
E AndroidRuntime:       at android.os.Parcel.createException(Parcel.java:2995)
E AndroidRuntime:       at android.os.Parcel.readException(Parcel.java:2978)
E AndroidRuntime:       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
E AndroidRuntime:       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
E AndroidRuntime:       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
E AndroidRuntime:       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
E AndroidRuntime:       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
E AndroidRuntime:       at android.content.ContentResolver.openInputStream(ContentResolver.java:1518)
E AndroidRuntime:       at hu.vmiklos.plees_tracker.DataModel.importData(DataModel.kt:163)
```

I.e. we just work with an input stream, but in case that's backed with some network stuff, Android is unhappy. What is the actual source here, Nextcloud?

**Comment by foss-** [comment]
Y, test was done with Import happening from a file located in Nextcloud folder.

**Comment by vmiklos** [comment]
Nice, I can reproduce this, thanks.

**Comment by vmiklos** [comment]
Works for me now, will cut a next release in 2-3 weeks.
