### ISSUE TITLE
Possibility to synchronise tracks with calendar 

### ISSUE THREAD

**Issue by petrhejna** [vmiklos/plees-tracker#41]
The description is from here:

https://github.com/vmiklos/plees-tracker/issues/29

The tracks of sleep will be synchronised to given (by setting) calendar.

It will serve as both as visualisation and backup.

**Comment by vmiklos** [comment]
Thanks @ed-george for implementing this nice feature! I plan to cut a new release during the next week that will contain this, if you prefer not building yourself but updating via fdroid.
