### ISSUE TITLE
ArrowOS: export to Nextcloud failed when plees-tracker.csv file already exists

### ISSUE THREAD

**Issue by foss-** [vmiklos/plees-tracker#414]
**Reproducer steps**
1. export to file from plees-tracker and use default filename
2. export a second time, again using default filename, this time while a file with that name already exsists.
3. Third step

**Actual result**
`Export failed: java.io.FileNotFoundException: Failed t...` and exported file has 0 B.

**Expected behavior**
Ask user to either overwrite existing file or rename the new export filename.

Logcat sent via email.

**Comment by vmiklos** [comment]
Yes, I can reproduce this one. Export to a folder on the phone works just fine (Android will pick `plees-tracker.csv`, then `plees-tracker (1).csv` and so on), but not export to Nextcloud.

Say again, what was some other app where this works fine? K-9 Mail?

**Comment by foss-** [comment]
Maybe this is not solvable? Just tested K-9 Mail export and when the exported file already exists, export fails. K-9 Mail shows `Failed to export settings`.

This is certainly an edge case since export isn't usually done multiple times. If you want to just close this, feel free to do so.

**Comment by vmiklos** [comment]
OK, let's focus on #407 that sounds more interesting. Possibly the root of the problem in this case is on the Nextcloud side, perhaps they could implement some auto-rename feature on collision, similar to what Android itself does for local files.
