### ISSUE TITLE
Show zero instead of empty text when no sleeps are recorded

### ISSUE THREAD

**Issue by goldbattle** [vmiklos/plees-tracker#436]
**Reproducer steps**
Just updated to 7.6.4.
Enabled automatic backups and display of average sleep length.
Return to the start screen and all my past recordings disappear.

**Actual result**
My tracks are gone.
I can still see there are some statistics that show that I have some sleeps..

![Screenshot_20231227_154840_Plees Tracker.jpg](https://github.com/vmiklos/plees-tracker/assets/2222562/d45ce5aa-1ab4-40d8-869f-331c56c009a1)
![Screenshot_20231227_154836_Plees Tracker.jpg](https://github.com/vmiklos/plees-tracker/assets/2222562/b0ae82a9-7aae-4d6f-b88a-6edce3a852da)

I exported and it seems they are still recorded possibly? Should I try to reimport this csv?

![Screenshot_20231227_155143_Sheets.jpg](https://github.com/vmiklos/plees-tracker/assets/2222562/d8cdb236-1df5-4d54-b35d-de6b892f63d0)

**Expected behavior**
To not lose all my historical tracks. I have no backups, so everything is lost it seems?

**Comment by vmiklos** [comment]
Sorry to hear that seems to be a data loss!

I just tried enabling automatic backup with a clean user profile and can't trivially reproduce this problem. Does it happen to you all the time you perform these steps or it happened only once?

Also, does this only happen with your phone or does it also happen in the emulator?

Last, does this happen even after you restart the app?

The internal storage is just sqlite and the stats are always calculated from scratch, so if you see your sleeps in the stats, then probably they are in the DB. This would suggest the DB is all fine, but the main activity's live update somehow gets confused and shows no sleeps. Does this still happen after you kill the app + start it again? I.e. is this a problem when you already changed your settings but the already running app tries to adapt itself to the new setting?

Let's try to clarify the reproducer steps to reach a state when this happens in a from-scratch emulator run, then it would be possible to debug this. Thanks.

**Comment by goldbattle** [comment]
I was unable to pull out the database over adb, so not sure what I can do to provide.
I was able to record new sleeps fine, it seems the interface is just empty when I have not done any recent sleeps.
Seems that the history on the main menu is maybe the last weeks worth as compared to a list of the most recent ones.

![image](https://github.com/vmiklos/plees-tracker/assets/2222562/774ca648-f7cc-498b-b73d-8122988bc580)
![image](https://github.com/vmiklos/plees-tracker/assets/2222562/17b04cec-5d5c-4797-b97c-acb4da73142c)

I expected to see a list of my recent past sleeps, and then if there are no sleeps in the last week, it should read zero.
Should this be fixed or is this expected?

So I don't think there is any data lost, just that after changing a setting it seems to have refreshed the main page.

**Comment by vmiklos** [comment]
> Should this be fixed or is this expected?

In case you go to the "..." menu -> Settings and dashboard duration is set to "last week", then it's indeed expected that the main activity won't show sleeps other than during the last week.

So at the end this was just confusion on how the app works? Or is there something to fix here?

**Comment by goldbattle** [comment]
I think it should show zero instead of empty text.

**Comment by vmiklos** [comment]
OK, that's finally actionable. :-)
