### ISSUE TITLE
[FeatureRequest] Add option for median instead of mean

### ISSUE THREAD

**Issue by le-jun** [vmiklos/plees-tracker#437]
Would it be possible to add an option for median instead of mean? I'd rather know that I tend to sleep this much daily (or for each sleep including naps) than for it to be under influence of, say, sick days where I undersleep or oversleep. In a way, this is complementary to #388.

**Comment by vmiklos** [comment]
Sure, it would be reasonably straightforward to add this. Are you interested in trying to do this yourself?

**Comment by le-jun** [comment]
Ha, I can't code for my life so I'll pass on this. But I'll take notes about your way of doing it!

**Comment by vmiklos** [comment]
app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt:411 is where we currently produce a list of daily sums, and then count the average of this list. I believe that's where we can conditionally do a median instead.

**Comment by vmiklos** [comment]
I'll probably cut a new release next weekend if you want this from fdroid and not building from source.

**Comment by vmiklos** [comment]
Still there, care to file a follow-up issues for that piece? Thanks.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/vmiklos/plees-tracker/issues/437#issuecomment-2130325386

@vmiklos, gladly: https://github.com/vmiklos/plees-tracker/issues/474#issue-2316252989
