### ISSUE TITLE
Changing calculation method from mean to median necessitates forced app reinitialization.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [vmiklos/plees-tracker#474]
#### **Reproducer steps**

Change the calculation method from mean to median.

#### **Actual result**

Paraphrased, as https://github.com/vmiklos/plees-tracker/issues/437#issuecomment-2130253352:~:text=One%20limit%20is%20that%20currently%20these%20settings%20don't%20trigger%20a%20recalc%20of%20the%20stats%2C%20so%20if%20you%20switch%20from%20average%20to%20median%20in%20the%20preferences%2C%20you%20need%20to%20kill%20the%20app%20(task%20list%2C%20remove%20the%20app%2C%20start%20again)%20to%20see%20the%20effect%20of%20the%20setting.%20It%20could%20be%20a%20follow%2Dup%20issue%20to%20not%20require%20this%20restart explains:

> One limit is that currently, [the option to change from mean to median] doesn't trigger a recalc of the stats, so if you switch from average to median in the preferences, you need to kill the app (task list, remove the app, start again) to see the effect of the setting. It could be a follow-up issue to not require this restart.

#### **Expected behavior**

ForceD reinitialization shouldn't be necessary.

**Comment by vmiklos** [comment]
Confirmed.
