### ISSUE TITLE
New stat that sums up sleeps / day, and then counts the avg

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#5]
What do you use it for?

**Comment by vmiklos** [comment]
The app is meant to help you give your body the rest it needs via gamification. Do you think this should be added to README.md? I thought it's obvious, but perhaps it is not.

**Comment by aleksejrs** [comment]
When do ''you'' press the button, and how do ''you'' use the stats?

Since I don't sleep regularly (and I guess somebody who decides to use the program is likely not to), I don't just press it when I go to bed and when I get up. So calling a sleep session a "night" doesn't make sense to me.

**Comment by vmiklos** [comment]
The primary use-case is 1 sleep / day, so your guess is wrong. :-) My usage is simply making sure the average doesn't go below 8h, because I know I need that. (Other people may need 6h, the app doesn't care.)

I assume then what you need is better support for your multiple sleeps / day: what about a new avg that sums up sleeps / day, and then counts the avg of that? Would that be your use-case?

(What counts is "sleeps" of the day is a bit unclear, perhaps we could approximate that by grouping the sleeps that ends the same day.)

**Comment by aleksejrs** [comment]
> I assume then what you need is better support for your multiple sleeps / day: what about a new avg that sums up sleeps / day, and then counts the avg of that? Would that be your use-case?

I'm interested in that. I don't know how pieces of sleep actually add up.

Related stuff: https://supermemo.guru/wiki/Biphasic_life
"SleepChart" seems to accept input similar to what Plees Tracker accepts. Anki records rating times and there is an addon that writes pairs of ratings, but I don't recall which one right now (probably something about consolidation, but then it's not in the official repositories).

**Comment by vmiklos** [comment]
OK, renaming the issue to make it more actionable. With that in place, this makes sense to me.

**Comment by vmiklos** [comment]
Fixed on master. Are you able to test this or are you waiting for a new fdroid release?

**Comment by aleksejrs** [comment]
I installed it from F-Droid and see strange numbers. I hope to check the csv tomorrow.

* Nights 2362
* Average 3:27:06
* Daily 95:55:11

**Comment by SebiderSushi** [comment]
Is it possible that "Daily" ignores days with no sleep at all?
I think these should be taken into account as days with 0 hours of sleep.

**Comment by vmiklos** [comment]
@SebiderSushi that sounds like a reasonable request, could you please open a dedicated issue for it? This one is already closed. I issue, one fix commit ideally :-)
