### ISSUE TITLE
There should be Graph / Chart Option on Weekly / Monthly sleep pattern

### ISSUE THREAD

**Issue by zaheernathani** [vmiklos/plees-tracker#51]
There should be Graph / Chart Option on Weekly / Monthly sleep pattern

**Comment by vmiklos** [comment]
The current stats are: last 7 days, this year, all time. It would be useful to describe in more detail what would you like to chart exactly.

What should be the title, the x axis and the y axis? And what chart type, a line-only chart?

**Comment by ilippert** [comment]
I would love a representation that tells me that 90% of sleep periods have length between a and b. One bar per Unit (week/month/year), and the deviation from the means.

**Comment by vmiklos** [comment]
That's indeed more concrete than the original request. :-) Are you interested in looking into this yourself?

I imagine a bit of research is needed what is a sane chart library to use, and the actual charting.

If not, at least putting together a mockup would be useful to show what exactly do you request.

**Comment by ilippert** [comment]
> That's indeed more concrete than the original request. :-) Are you interested in looking into this yourself?
> 
> I imagine a bit of research is needed what is a sane chart library to use, and the actual charting.
> 
> If not, at least putting together a mockup would be useful to show what exactly do you request.

I don't have any significant programming skills, but am happy to sketch a mockup, easiest for me would actually be by hand ;)

**Comment by vmiklos** [comment]
Sure, you can attach an image to this issue.

**Comment by vmiklos** [comment]
#115 more or less fixed this, if something is missing, let's have a follow-up issue for it.
