### ISSUE TITLE
Ideas for more statistics

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#6]
Let's post ideas for more stats, one idea per comment (so that people can just use reactions on them).

**Comment by aleksejrs** [comment]
Median sleep length, in addition of the existing average.

**Comment by aleksejrs** [comment]
The total amount of sleep in the last few days, and the average per day. For example, if you've slept
12:08 total on one day, then 07:05, then 06:05, PT might show a table like:

```
            Total Per day
Last 1 day  06:05  06:05
Last 2 days 13:10  06:35
Last 3 days 25:02  08:20
```

**Comment by vmiklos** [comment]
Let me scope this a bit. Currently you get a stat on all of the sleeps. I could add a new menu item to launch a new activity where you could get not only your all time (two) averages, but also for limited periods like last 7 days or year-to-date.

This would more or less what you described above, but more actionable. :-)

**Comment by vmiklos** [comment]
Looks like this:

![Screenshot_20200605-235623](https://user-images.githubusercontent.com/13838/83926097-2cab3f80-a789-11ea-9e9b-dfcd67588bcc.png)

**Comment by vmiklos** [comment]
Fixed on master, can be tested with a local build or in the next release.
