### ISSUE TITLE
Make text and button sizes configurable

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#7]
The text is too small for me, and I can't even see the state of the button well.

**Comment by vmiklos** [comment]
85f9deb6ce5ba562d39a7017c8e3a26f4cc2bac8 increased the font size at a number of places, see the updated screenshot at https://raw.githubusercontent.com/vmiklos/plees-tracker/master/app/src/main/play/listings/en-US/graphics/phone-screenshots/1.png

Am I right this is already large enough, so no need to make them configurable?

**Comment by aleksejrs** [comment]
I don't see how that is larger.

**Comment by aleksejrs** [comment]
The text may have become imperceptibly larger, and the button has even become smaller!

**Comment by vmiklos** [comment]
Nah, its size is unchanged, just the text is larger. Random example: Google keep seem to have the same Floating Action Button size. Do you know any other app where the FAB size is configurable?

**Comment by aleksejrs** [comment]
> Do you know any other app where the FAB size is configurable?

No, because of the many apps I have installed, I can only recall two or three that have a FAB at all, and the only one of them that has more than one FABs with different meanings uses different colors and different contexts for them; and Plees Tracker is the only one that needs to be used around sleeping.

**Comment by vmiklos** [comment]
https://material.io/components/buttons-floating-action-button/

Does it help if I make the FAB an extended one where the start/stop string is visible, so the button is much wider? The height currently conforms to the material design guidelines, I don't want to break that.

**Comment by vmiklos** [comment]
https://blog.usejournal.com/expand-collapse-fab-on-scrolling-like-googles-message-app-484df2d9d246 actually these days it's common to expand the fab by default, we could do that and it would also help you with your size problems.

**Comment by vmiklos** [comment]
I've implemented the above idea now, closing.
