### ISSUE TITLE
Improve deletion undo usability

### ISSUE THREAD

**Issue by aleksejrs** [vmiklos/plees-tracker#8]
The undo UI has issues:
1. It covers the start/stop button. If I delete what I wanted to delete, I can't restart immediately.
2. It disappears too soon. If I delete what I don't want to delete, I have no time to recognize that.
3. You may not recognize that you've deleted the wrong thing if you are actually sleepy. It could show some details like the duration and the ending time.

**Comment by aleksejrs** [comment]
Sometimes I want to stop the timer and delete the result, but if I delete before stopping, the wrong  record is deleted.

**Comment by aleksejrs** [comment]
How about marking an entry as deleted clearly before actually removing it from the UI? For example, striking the text out and adding an Undo button near it (hope there is space).

**Comment by vmiklos** [comment]
> It covers the start/stop button. If I delete what I wanted to delete, I can't restart immediately.

Indeed, the snackbar containing the undo button could shift up the floating action button (start stop button), e.g. gmail does this.

**Comment by vmiklos** [comment]
Fixed on master: either build from source to see it in action, or i'll probably cut a next release in May.

**Comment by vmiklos** [comment]
6.2 is out, containing this.
