### ISSUE TITLE
Automatic backup shows as enabled even when folder is not selected

### ISSUE THREAD

**Issue by usashiki** [vmiklos/plees-tracker#90]
**Reproducer steps**

1. Attempt to enable Automatic backup, opening Files app
2. Refuse to select a folder by repeated pressing back button or closing the app
3. Automatic backup shows as enabled in settings even though no folder was selected

**Actual result**
Unclear but I assume no backup occurs.

**Expected behavior**
Automatic backup goes back to disabled if no folder is selected.

Related, it would be nice if the folder selected were shown if Automatic backup is enabled.

**Comment by vmiklos** [comment]
Makes sense.

**Comment by vmiklos** [comment]
You can build from sources locally or this will be in 7.1.0, to be released early Feb.
