### ISSUE TITLE
Delay when adding new sleep

### ISSUE THREAD

**Issue by usashiki** [vmiklos/plees-tracker#91]
As I mentioned in #88 (apologies for all the issues), I recently imported a few years worth of sleep data from Sleep as Android into Plees, and I noticed that now when I try to add a new sleep there is a significant delay, around 10 seconds, between tapping stop and seeing the new sleep appear on the dashboard. 

Video: https://user-images.githubusercontent.com/2847492/104951028-996cf600-5976-11eb-81be-b36cdbbe78aa.mp4

I assume this is a scaling problem with the number of sleeps, so perhaps #88 might help with this, though it isn't a complete solution.

**Comment by usashiki** [comment]
Hmm, I tried clearing my app storage to make sure the delay wasn't occuring with no sleeps (it didn't), and now I can't reproduce the delay after importing my old data back. I guess I'll close this then, I'll reopen if it comes back.

**Comment by vmiklos** [comment]
Import was slow in th past, the recycler view was updated after every single added sleep, but as you found, that's already fixed. I'm currently not aware of other perf problems :-)
