### ISSUE TITLE
Request: start/stop widget for home screen

### ISSUE THREAD

**Issue by polyonymous** [vmiklos/plees-tracker#92]
Hi. I just downloaded this app and it seems great - does what I need and nothing I don't need. The one addition I would love is a simple widget on my home screen that I could tap to start and stop a sleep session.

**Comment by vmiklos** [comment]
I just have the app icon on my home screen, then it takes 2 taps to start or stop a sleep.

But sure, could add a widget. Are you interested in looking at this yourself? I imagine it needs a bit of research how do you add a widget, but then you would just call the same function as the event handler of the start/stop button on the main activity.
