### ISSUE TITLE
Quick Settings tile to start/stop sleep

### ISSUE THREAD

**Issue by usashiki** [vmiklos/plees-tracker#94]
Similar to #92, it would be cool if Plees could provide a Quick Settings tile to start and stop sleep. The benefit here is that it would be possible to start/stop sleep without having to open the app, e.g. from the lock screen.

**Comment by vmiklos** [comment]
Do you have an example open source app that provides such a tile? It would be interesting to see that in action

**Comment by usashiki** [comment]
Hmm, going off what I've got on my phone right now, Geometric Weather (https://github.com/geometric-weather-foss/GeometricWeather, open app),
Tasks (https://github.com/tasks/tasks, create new task), and ProtonVPN (https://github.com/ProtonVPN/android-app, enable/disable VPN) provide tiles. 

<details>
<summary>Screenshot</summary>

![Screenshot_20210124-111028_1](https://user-images.githubusercontent.com/2847492/105640819-f5cb8c00-5e34-11eb-93cc-a48a5d243d8e.png)

</details>

**Comment by vmiklos** [comment]
Thanks, I have to confess I didn't realize apps can also provide these quick tiles. :-) Makes sense, once #92 is sorted out, which is probably easier (widgets is an older feature).

**Comment by vmiklos** [comment]
One possible follow-up improvement would be to just silently start/stop the tracking and no go via the main activity. This is not trivial though: the sleep service is started when the main activity goes to background, also I'm not sure how to do db operations without a view model, which is available only inside an activity.
